import { Suppliers } from "./@types";

export const smeSectors = [
    "Agriculture and Agribusiness",
    "Manufacturing",
    "Retail and Wholesale",
    "Healthcare and Pharmaceuticals",
    "Technology and IT Services",
    "Education and Training",
    "Real Estate and Construction",
    "Tourism and Hospitality",
    "Financial Services",
    "Transportation and Logistics",
    "Creative Industries",
    "Telecommunications",
    "Professional Services",
    "Media and Communications",
    "Renewable Energy and Environmental Services",
    "Beauty and Personal Care",
    "Food and Beverage",
    "Fashion and Apparel",
    "Home Improvement and Maintenance",
    "Event Management and Planning",
    "Pet Care and Services",
    "Sports and Fitness",
    "Transportation and Automotive Services",
    "Cleaning and Sanitation Services",
    "Crafts and Artisanal Products",
    "Logistics and Supply Chain Solutions",
    "Waste and Recycling Services"
  ];

  export const arrayBox: Suppliers[] =[
    { id: 1, name: "James Carter", phone: "+2347012345678", location: "Lagos", latitude: 6.5244, longitude: 3.3792, alterEgo: "The Provider", description: "Reliable and efficient" },
    { id: 2, name: "Olivia Reed", phone: "+2347023456789", location: "Abuja", latitude: 9.0765, longitude: 7.3986, alterEgo: "The Guardian", description: "Known for quality service" },
    { id: 3, name: "Liam Walker", phone: "+2347034567890", location: "Ibadan", latitude: 7.3775, longitude: 3.9470, description: "Quick deliveries across the state" },
    { id: 4, name: "Emma Brooks", phone: "+2347045678901", location: "Kano", latitude: 12.0022, longitude: 8.5919, alterEgo: "Speedster", description: "Fast and dependable" },
    { id: 5, name: "Michael Kim", phone: "+2347056789012", location: "Port Harcourt", latitude: 4.8156, longitude: 7.0498, description: "Affordable and trustworthy" },
    { id: 6, name: "Sophia Turner", phone: "+2347067890123", location: "Benin City", latitude: 6.3392, longitude: 5.6258, alterEgo: "The Conqueror", description: "Broad inventory and resources" },
    { id: 7, name: "William Lee", phone: "+2347078901234", location: "Jos", latitude: 9.8965, longitude: 8.8583, description: "Eco-friendly solutions" },
    { id: 8, name: "Grace O'Connor", phone: "+2347089012345", location: "Kaduna", latitude: 10.5105, longitude: 7.4165, alterEgo: "The Optimizer", description: "Excellent customer support" },
    { id: 9, name: "Benjamin Scott", phone: "+2347090123456", location: "Enugu", latitude: 6.5246, longitude: 7.5086, description: "Flexible order quantities" },
    { id: 10, name: "Chidi Nwosu", phone: "+2348101234567", location: "Abeokuta", latitude: 7.1604, longitude: 3.3485, alterEgo: "The Planner", description: "Strategic supply solutions" },
    { id: 11, name: "Ngozi Okafor", phone: "+2348112345678", location: "Makurdi", latitude: 7.7337, longitude: 8.5214, description: "Specializes in bulk orders" },
    { id: 12, name: "Adebayo Adesina", phone: "+2348123456789", location: "Owerri", latitude: 5.4851, longitude: 7.0348, alterEgo: "Bulk Master", description: "Deals in wholesale" },
    { id: 13, name: "Fatima Bello", phone: "+2348134567890", location: "Ilorin", latitude: 8.4966, longitude: 4.5421, description: "High-quality products" },
    { id: 14, name: "Yusuf Ibrahim", phone: "+2348145678901", location: "Sokoto", latitude: 13.0059, longitude: 5.2476, alterEgo: "Eco Advocate", description: "Sustainable practices" },
    { id: 15, name: "Chioma Obi", phone: "+2348156789012", location: "Calabar", latitude: 4.9589, longitude: 8.3269, description: "On-time delivery specialist" },
    { id: 16, name: "Bola Adewale", phone: "+2348167890123", location: "Uyo", latitude: 5.0283, longitude: 7.9266, alterEgo: "Precisionist", description: "Accurate order fulfillment" }
];

export const nigeriaStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
  "FCT (Federal Capital Territory)"
];