export const smeSectors = [
    "Agriculture and Agribusiness",
    "Manufacturing",
    "Retail and Wholesale",
    "Healthcare and Pharmaceuticals",
    "Technology and IT Services",
    "Education and Training",
    "Real Estate and Construction",
    "Tourism and Hospitality",
    "Financial Services",
    "Transportation and Logistics",
    "Creative Industries",
    "Telecommunications",
    "Professional Services",
    "Media and Communications",
    "Renewable Energy and Environmental Services",
    "Beauty and Personal Care",
    "Food and Beverage",
    "Fashion and Apparel",
    "Home Improvement and Maintenance",
    "Event Management and Planning",
    "Pet Care and Services",
    "Sports and Fitness",
    "Transportation and Automotive Services",
    "Cleaning and Sanitation Services",
    "Crafts and Artisanal Products",
    "Logistics and Supply Chain Solutions",
    "Waste and Recycling Services"
  ];
  